name = "fortran-astrodynamics-toolkit"
author = "Jacob Williams"
copyright  = "Copyright (c) 2014-2022, Jacob Williams"
license = "BSD-3"
description = "A Modern Fortran Library for Astrodynamics"
homepage = "https://github.com/jacobwilliams/fortran-astrodynamics-toolkit"
keywords = ["astrodynamics"]

[dev-dependencies]
pyplot-fortran= { git = "https://github.com/jacobwilliams/pyplot-fortran", rev = "3.3.0" }

[build]
auto-executables = true
auto-examples = true
auto-tests = true

[library]
source-dir = "src"

[install]
library = true

# [[test]]
# name = "lambert_test"
# source-dir = "tests/lambert"
# main = "lambert_test.f90"

# [[test]]
# name = "lambert_test_2"
# source-dir = "tests/lambert"
# main = "lambert_test_2.f90"

# [[test]]
# name = "crtbp_test"
# source-dir = "tests/crtbp"
# main = "crtbp_test.f90"

# [[test]]
# name = "dro_test"
# source-dir = "tests/dro"
# main = "dro_test.f90"

# [[test]]
# name = "elements_test"
# source-dir = "tests/elements"
# main = "elements_test.f90"

# [[test]]
# name = "halo_test"
# source-dir = "tests/halo"
# main = "halo_test.f90"

# [[test]]
# name = "kepler_tests"
# source-dir = "tests/kepler"
# main = "kepler_tests.f90"

# [[test]]
# name = "cw_test"
# source-dir = "tests/cw_test"
# main = "cw_test.f90"

# [[test]]
# name = "ephemeris_comparison"
# source-dir = "tests/ephemeris"
# main = "ephemeris_comparison.f90"

# [[test]]
# name = "fat_tests"
# source-dir = "tests/unit_tests"
# main = "fat_tests.f90"

# [[test]]
# name = "gravity_test"
# source-dir = "tests/gravity"
# main = "gravity_test.f90"

# [[test]]
# name = "geodetic_test"
# source-dir = "tests/geodetic_test"
# main = "geodetic_test.f90"
